// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api-docs": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api-docs" | "/home";
  };
  "routes/api-docs.tsx": {
    id: "routes/api-docs";
    page: "/api-docs";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
};

type RouteModules = {
  "root": typeof import("./src/client/root.tsx");
  "routes/api-docs": typeof import("./src/client/routes/api-docs.tsx");
  "routes/_index": typeof import("./src/client/routes/_index.tsx");
  "routes/home": typeof import("./src/client/routes/home.tsx");
};